
#-----------------#
#   WARNING:
#   ALPHA VERSIONS ARE NOT FOR USAGE OR DISTRIBUTION!
#-----------------#

#SkriptDrugs Version 0.2 Alpha
#By GrassyMoss
#Note: FernWeed is used as a variable to ensure that you cannot get high off of all ferns. Only the ferns that are actually weed. The same type of variables are applied to every other drug.
#Weed = Super Ferns --- Shrooms = Magic Mushrooms --- Cocaine = Power Powder
#Each drug is given some kind of special formatting or color in the name to ensure that is actually a drug, and to separate it from products re-named by players using anvils.
#If you modify the code that is intended for distribution through Cobalt Network, please leave your developer name at the sections you add, remove, or modify.
#To do: Add overdose consequences, add more drug variety, test for bugs, add /drugs command with info.
#Possibly combine all drugs into one "rightclick" event?

#--- Weed / Cannabis / Marijuana
on break of fern:
	set {FernWeed} to fern named "&2Weed"
	chance of 8%
	give player {FernWeed} #<--- Do you end up with fern AND weed? If so, please add 'cancel event' or similar
	message "&8[&aDrugs&8]&r You found some &2Super Ferns!&r!"
	
on rightclick:
	player is holding {FernWeed}:
		set {WeedHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &2Weed&r!"
		chance of 50%:
			apply hunger 1 to the player for 30 seconds
			apply absorption 1 to the player for 15 seconds
		chance of 50%:
			apply hunger 4 to the player for 8 seconds
			apply regeneration 1 to the player for 2 seconds
		remove {FernWeed} from the player

		
#--- Magic Mushrooms / Shrooms
on break of mushroom:
	set {Shroom} to mushroom named "&cMagic Mushrooms"
	chance of 8%
	give player {Shroom}
	message "&8[&aDrugs&8]&r You found some &cMagic Mushrooms&r!"
	
on rightclick:
	player is holding {Shroom}:
		set {ShroomHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &cMagic Mushrooms&r!"
		chance of 50%:
			apply water breathing 1 to the player for 70 seconds
			apply blindness 1 to the player for 65 seconds
		chance of 50%:
			apply poison 1 to the player for 15 seconds
			apply invisibility 1 to the player for 30 seconds
		remove {Shroom} from the player
		
		
#--- Cocaine
on break of sugar cane:
	set {Cocaine} to sugar named "&lPower Powder"
	chance of 8%
	give player {Cocaine}
	message "&8[&aDrugs&8]&r You found some &lPower Powder&r!"
	
on rightclick:
	player is holding {Cocaine}:
		set {CocaineHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &lPower Powder&r!"
		chance of 50%:
			apply confusion 3 to the player for 40 seconds
			apply speed 3 to the player for 50 seconds
		chance of 50%:
			apply mining fatigue 2 to the player for 70 seconds
			apply jump boost 3 to the player for 60 seconds
		remove {Cocaine} from the player
		
		
#--- Command
command /drugs [<text=""] 