#----
#   WARNING:
#   Alpha versions maybe be unstable, nonfunctional, or very buggy!
#----

#----
#SkriptDrugs
# Version 0.4 Alpha
# - By GrassyMoss
#----

#----
#Dependencies:
# - Latest version of Skript
#----

#----
#Notes:
# - Variables are used to store the item information and name to be sure that you cannot get high off of all of those items, only the ones that are specifically designated drugs.
# - Each drug is given some kind of special formatting or color in the name to ensure that is actually a drug, and to separate it from products re-named by players using anvils.
# - Will add options section in a future update to help allow server admins to customize functionality. 
#----

#----
#List of drugs and their in-game names:
# - Weed = Super Ferns
# - Shrooms = Magic Mushrooms
# - Cocaine = Power Powder
# - Meth = Power Crystals
# - Peyote = Glistening Prickles
# - Moonshine = Moonshine
#----


#--- Weed / Cannabis / Marijuana
on break of fern:
	set {drugs.weed} to fern named "&2Super Ferns&r"
	chance of 8%:
		give player {drugs.weed}
		message "&8[&aDrugs&8]&r You found some &2Super Ferns!&r!"
	
on rightclick:
	player is holding {drugs.weed}:
		add 1 to {drugs.high.%player%}
		message "&8[&aDrugs&8]&r You are now high on &2Super Ferns&r!"
		chance of 50%:
			apply hunger 1 to the player for 60 seconds
			apply absorption 1 to the player for 35 seconds
			remove {drugs.weed} from the player
			wait 60 seconds
			subtract 1 from {drugs.high.%player%}
			exit
		else:
			apply hunger 4 to the player for 30 seconds
			apply regeneration 1 to the player for 8 seconds
			remove {drugs.weed} from the player
			wait 30 seconds
			subtract 1 from {drugs.high.%player%}
			exit
			
		
#--- Magic Mushrooms / Shrooms
on break of mushroom:
	set {drugs.shroom} to mushroom named "&cMagic Mushrooms"
	chance of 8%:
		give player {drugs.shroom}
		message "&8[&aDrugs&8]&r You found some &cMagic Mushrooms&r!"
	
on rightclick:
	player is holding {drugs.shroom}:
		add 1 to {drugs.high.%player%}
		message "&8[&aDrugs&8]&r You are now high on &cMagic Mushrooms&r!"
		chance of 50%:
			apply water breathing 1 to the player for 70 seconds
			apply blindness 1 to the player for 65 seconds
		else:
			apply poison 1 to the player for 15 seconds
			apply invisibility 1 to the player for 30 seconds
		remove {drugs.shroom} from the player
		wait 1 tick
		set {drugs.high.shroom.%player%} to false
		
		
#--- Cocaine
on break of sugar cane:
	set {drugs.cocaine} to sugar named "&lHappy Powder&r"
	chance of 8%:
		give player {drugs.cocaine}
		message "&8[&aDrugs&8]&r You found some &lHappy Powder&r!"
	
on rightclick:
	player is holding {drugs.cocaine}:
		add 1 to {drugs.high.%player%}
		message "&8[&aDrugs&8]&r You are now high on &lHappy Powder&r!"
		chance of 50%:
			apply confusion 3 to the player for 40 seconds
			apply speed 3 to the player for 50 seconds
		chance of 50%:
			apply mining fatigue 2 to the player for 70 seconds
			apply jump boost 3 to the player for 60 seconds
		remove {drugs.cocaine} from the player
		wait 1 tick
		set {drugs.high.cocaine.%player%} to false

#--- Meth
on break of ice:
	set {drugs.meth} to ice named "&bPower Crystals&r"
	chance of 8%:
		give player {drugs.meth}
		message "&8[&aDrugs&8]&r You found some &bPower Crystals&r!"
	
on rightclick:
	player is holding {drugs.meth}:
		add 1 to {drugs.high.%player%}
		message "&8[&aDrugs&8]&r You are now high on &bPower Crystals&r!"
		chance of 50%:
			apply speed 2 to the player for 80 seconds
			apply instant damage 1 to the player for 1 second
		chance of 50%:
			apply saturation 3 to the player for 45 seconds
			apply wither 1 to the player for 8 seconds
		remove {drugs.meth} from the player
		wait 1 tick
		set {drugs.high.meth.%player%} to false

#--- Peyote
on break of cactus:
	set {drugs.peyote} to cactus named "&eGlistening Prickles&r"
	chance of 8%:
		give player {drugs.peyote}
		message "&8[&aDrugs&8]&r You found some &eGlistening Prickles&r"
	
on rightclick:
	player is holding {drugs.peyote}:
		add 1 to {drugs.high.%player%}
		message "&8[&aDrugs&8]&r You are now high on &eGlistening Prickles&r"
		chance of 50%:
			apply blindness 1 to the player for 45 seconds
			apply haste 2 to the player for 45 seconds
		chance of 50%:
			apply nausea 1 to the player for 40 seconds
			apply resistance 2 to the player for 25 seconds
		remove {drugs.peyote} from the player
		wait 1 tick
		set {PeyoteHigh.%player%} to false

#--- Moonshine
on break of wheat:
	set {Barley} to wheat named "&6Barley&r"
	chance of 8%:
		give player {Barley}
		message "&8[&aDrugs&8]&r You found some &6Barley&r! Use it to make moonshine!"
		
on click on a cauldron holding awkward potion:
	set {Moonshine} to awkward potion named "&9Moonshine&r"
	player has {Barley}:
		remove awkward potion from the player
		remove {Barley} from the player
		message "&8[&aDrugs&8]&r You made some &9Moonshine&r!"
		wait 1 tick
		give player {Moonshine}
	
on consume:
	item is {Moonshine}:
		add 1 to {drugs.high.%player%}
		message "&8[&aDrugs&8]&r You are now drunk with &9Moonshine&r!"
		chance of 50%:
			apply nausea 2 to the player for 60 seconds
			apply health boost 1 to the player for 45 seconds
		chance of 50%:
			apply weakness 2 to the player for 50 seconds
			apply fire resistance to the player for 50 seconds
		remove {Moonshine} from the player
		wait 1 tick
		set {Drunk.%player%} to false

#--- Overdose <--- Doesn't work yet
#on click:
#	{drugs.high.weed.%player%} is true:
#		{drugs.high.cocaine.%player%} is true:
#			{drugs.high.shroom.%player%} is true:
#				{drugs.high.meth.%player%} is true:
#					{PeyoteHigh.%player%} is true:
#						{Drunk.%player%} is true:
#							chance of 60%
#							message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
#							kill the player
#						else:
#							chance of 50%
#							message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
#							kill the player
#					else:
#						chance of 40%
#						message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
#						kill the player
#				else:
#					chance of 30%
#					message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
#					kill the player
#			else:
#				chance of 20%
#				message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
#				kill the player
#		else:
#			chance of 10%
#			message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
#			kill the player

#--- Command
command /drugs [<text="">]:
	description: Main command associated with the drugs add-on. Allows you to view help and info, along with the ability to create new drugs, if you have permission.
#	permission: Your permission here
#	permission message: &8[&aDrugs&8]&r You&4 do not&r have permission to use that drug command. View &a/drugs&r for help. #<--- Unused for now
	aliases: /drug
	trigger:
		if arg 1 is "", "cmd", "command", "about", "version" or "help":
			message "&a-&8-&a-&8[&a&lDrugs Help&8]&8-&a-&8-"
			send "No help here, sorry!"
			message "&a-&8-&a-&8-"
			exit
		if arg 1 is "list" or "drugs":
			message "&a-&8-&a-&8[&a&l List of drugs&8]&8-&a-&8-"
			message " - &2Super Fern&7 [Break Ferns]&r"
			message " "
			message " - &cMagic Mushrooms&7 [Break Mushrooms]"
			message " "
			message " - &lHappy Powder&7 [Break Sugar Cane]"
			message " "
			message " - &9Moonshine&7 [Click on cauldron with an awkward potion. Must have barley in inventory]"
			message " "
			message " - &bPower Crystals&7 [Break Ice]"
			message " "
			message " - &eGlistening Prickles&7 [Break Cactus]"
			message "&a-&8-&a-&8-"
			exit
		if arg 1 is "check", "over", "overdose", "dose" or "me":
			message "&8[&aDrugs&8]&r &cError: This command is not functioning right now.&r"
			exit
		else:
			message "&8[&aDrugs&8]&4 Error:&c Invalid command or arguments!"
			exit
			