
#-----------------#
#   WARNING:
#   ALPHA VERSIONS ARE NOT FOR USAGE OR DISTRIBUTION!
#-----------------#

#SkriptDrugs Version 0.3 Alpha
#By GrassyMoss

#Note: Variables are used to store the item information and name to be sure that you cannot get high off of all of those items, only the ones that are specifically designated drugs.
#Weed = Super Ferns --- Shrooms = Magic Mushrooms --- Cocaine = Power Powder
#Each drug is given some kind of special formatting or color in the name to ensure that is actually a drug, and to separate it from products re-named by players using anvils.
#If you modify the code that is intended for distribution through Cobalt Network, please leave your developer name at the sections you add, remove, or modify.
#To do: Add overdose consequences, add more drug variety, test for bugs, add /drugs command with info.
#Possibly combine all drugs into one "rightclick" event? <--- Explore benefits of this

#--- Weed / Cannabis / Marijuana
on break of fern:
	set {FernWeed} to fern named "&2Super Ferns&r"
	chance of 8%:
		give player {FernWeed}
		message "&8[&aDrugs&8]&r You found some &2Super Ferns!&r!"
	
on rightclick:
	player is holding {FernWeed}:
		set {WeedHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &2Super Ferns&r!"
		chance of 50%:
			apply hunger 1 to the player for 30 seconds
			apply absorption 1 to the player for 15 seconds
		chance of 50%:
			apply hunger 4 to the player for 8 seconds
			apply regeneration 1 to the player for 2 seconds
		remove {FernWeed} from the player

		
#--- Magic Mushrooms / Shrooms
on break of mushroom:
	set {Shroom} to mushroom named "&cMagic Mushrooms"
	chance of 8%:
		give player {Shroom}
		message "&8[&aDrugs&8]&r You found some &cMagic Mushrooms&r!"
	
on rightclick:
	player is holding {Shroom}:
		set {ShroomHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &cMagic Mushrooms&r!"
		chance of 50%:
			apply water breathing 1 to the player for 70 seconds
			apply blindness 1 to the player for 65 seconds
		chance of 50%:
			apply poison 1 to the player for 15 seconds
			apply invisibility 1 to the player for 30 seconds
		remove {Shroom} from the player
		
		
#--- Cocaine
on break of sugar cane:
	set {Cocaine} to sugar named "&lHappy Powder&r"
	chance of 8%:
		give player {Cocaine}
		message "&8[&aDrugs&8]&r You found some &lHappy Powder&r!"
	
on rightclick:
	player is holding {Cocaine}:
		set {CocaineHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &lHappy Powder&r!"
		chance of 50%:
			apply confusion 3 to the player for 40 seconds
			apply speed 3 to the player for 50 seconds
		chance of 50%:
			apply mining fatigue 2 to the player for 70 seconds
			apply jump boost 3 to the player for 60 seconds
		remove {Cocaine} from the player

#--- Meth
on break of ice:
	set {Meth} to ice named "&bPower Crystals&r"
	chance of 8%:
		give player {Meth}
		message "&8[&aDrugs&8]&r You found some &bPower Crystals&r!"
	
on rightclick:
	player is holding {Meth}:
		set {MethHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &bPower Crystals&r!"
		chance of 50%:
			apply speed 2 to the player for 80 seconds
			apply instant damage 1 to the player for 1 second
		chance of 50%:
			apply saturation 3 to the player for 45 seconds
			apply wither 1 to the player for 8 seconds
		remove {Meth} from the player

#--- Peyote
on break of cactus:
	set {Peyote} to cactus named "&eGlistening Prickles&r"
	chance of 8%:
		give player {Peyote}
		message "&8[&aDrugs&8]&r You found some &eGlistening Prickles&r"
	
on rightclick:
	player is holding {Peyote}:
		set {PeyoteHigh.%player%} to true
		message "&8[&aDrugs&8]&r You are now high on &eGlistening Prickles&r"
		chance of 50%:
			apply blindness 1 to the player for 45 seconds
			apply haste 2 to the player for 45 seconds
		chance of 50%:
			apply nausea 1 to the player for 40 seconds
			apply resistance 2 to the player for 25 seconds
		remove {Peyote} from the player

#--- Moonshine
on break of wheat:
	set {Barley} to wheat named "&6Barley&r"
	chance of 8%:
		give player {Barley}
		message "&8[&aDrugs&8]&r You found some &6Barley&r! Use it to make moonshine!"
		
on click on a cauldron holding awkward potion:
	set {Moonshine} to awkward potion named "&9Moonshine&r"
	player has {Barley}:
		remove awkward potion from the player
		remove {Barley} from the player
		message "&8[&aDrugs&8]&r You made some &9Moonshine&r!"
		wait 1 tick
		give player {Moonshine}
	
on consume:
	item is {Moonshine}:
		set {Drunk.%player%} to true
		message "&8[&aDrugs&8]&r You are now drunk with &9Moonshine&r!"
		chance of 50%:
			apply nausea 2 to the player for 60 seconds
			apply health boost 1 to the player for 45 seconds
		chance of 50%:
			apply weakness 2 to the player for 50 seconds
			apply fire resistance to the player for 50 seconds
		remove {Moonshine} from the player

#--- Overdose
on click:
	{WeedHigh.%player%} is true:
		{CocaineHigh.%player%} is true:
			{ShroomHigh.%player%} is true:
				{MethHigh.%player%} is true:
					{PeyoteHigh.%player%} is true:
						{Drunk.%player%} is true:
							chance of 60%
							message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
							kill the player
						else:
							chance of 50%
							message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
							kill the player
					else:
						chance of 40%
						message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
						kill the player
				else:
					chance of 30%
					message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
					kill the player
			else:
				chance of 20%
				message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
				kill the player
		else:
			chance of 10%
			message "&8[&aDrugs&8]&r You overdosed on drugs and died!"
			kill the player

#--- Command
command /drugs [<text="">] [<text="">] [<item>]:
	description: Main command associated with the drugs plugin. Allows you to view help and info, along with the ability to create new drugs, if you have permissions.
#	permission message: &8[&aDrugs&8]&r You&4 do not&r have permission to use that drug command. View &a/drugs&r for help. #<--- Unused for now
	aliases: /drugs
	trigger:
		arg 1 is "" or "help":
			message "&a-&8-&a-&8-&a-&8[&aDrugs&8]&8-&a-&8-&a-&8-"
			message "  "
			message "&7 Topic:&r &lDrugs Help&r"
			message "&7 Link:&r   &b> > >&n http://wiki.cobalt-mc.com/drugs &r&b< < <" #Wiki link doesn't work, write wiki page soon.
			message "  "
			message "&7&oClick on the blue link above to view the topic."
			message "&a-&8-&a-&8-&a-&8-&a-&8-&a-&8-&a-&8-&a-&8-"
		arg 1 is "list" or "drugs":
			message "&a-&8-&a-&8-&a-&8[&aDrugs&8]&8-&a-&8-&a-&8-"
			message "&7List of Drugs:"
			message " - &2Super Fern&r [Break Ferns]&r"
			message " - &cMagic Mushrooms&r [Break Mushrooms]"
			message " - &lHappy Powder&r [Break Sugar Cane]"
			message " - &9Moonshine&r [Click on cauldron with an awkward potion. Must have barley in inventory]"
			message " - &bPower Crystals&r [Break Ice]"
			message "&a-&8-&a-&8-&a-&8-&a-&8-&a-&8-&a-&8-&a-&8-"
		arg 1 is "check" or "me":
			message "&8[&aDrugs&8]&r High on &2Super Ferns&r: {WeedHigh.%player%}. High on &lHappy Powder&r: {CocaineHigh.%player%}."
			message "High on &cMagic Mushrooms&r: {ShroomHigh.%player%}. Drunk with &9Moonshine&r: {ShineDrunk.%player%}."
			message "High on &bPower Crystals&r: {MethHigh.%player%}."
		else:
			message "&8[&aDrugs&8]&r &4Invalid Command&r"